<?php

namespace common\tests\unit\models;

use common\models\Client;

class ClientTest extends \Codeception\Test\Unit
{
    protected function getValidClientData()
    {
        return [
            'client_code' => 'CLT-' . time(),
            'type' => Client::TYPE_INDIVIDUAL,
            'first_name' => 'John',
            'last_name' => 'Doe',
            'email' => 'john' . time() . '@test.com',
            'phone' => '9999999999',
        ];
    }

    public function testCreateValidClient()
    {
        $client = new Client();
        $client->load($this->getValidClientData(), '');

        $this->assertTrue($client->validate());
        $this->assertTrue($client->save());
        $this->assertNotNull($client->id);
    }

    public function testRequiredFields()
    {
        $client = new Client();

        $this->assertFalse($client->validate());

        $this->assertArrayHasKey('first_name', $client->errors);
        $this->assertArrayHasKey('email', $client->errors);
        $this->assertArrayHasKey('phone', $client->errors);

        // client_code is auto-generated → should NOT be required
        $this->assertArrayNotHasKey('client_code', $client->errors);
    }


    public function testInvalidEmail()
    {
        $data = $this->getValidClientData();
        $data['email'] = 'invalid-email';

        $client = new Client();
        $client->load($data, '');

        $this->assertFalse($client->validate());
        $this->assertArrayHasKey('email', $client->errors);
    }

    public function testUniqueClientCode()
    {
        $data = $this->getValidClientData();

        $client1 = new Client();
        $client1->load($data, '');
        $client1->save();

        $client2 = new Client();
        $client2->load($data, '');

        $this->assertFalse($client2->validate());
        $this->assertArrayHasKey('client_code', $client2->errors);
    }

    public function testCompanyRequiresCompanyName()
    {
        $data = $this->getValidClientData();
        $data['type'] = Client::TYPE_COMPANY;
        unset($data['company_name']);

        $client = new Client();
        $client->load($data, '');

        $this->assertFalse($client->validate());
        $this->assertArrayHasKey('company_name', $client->errors);
    }

    public function testCompanyWithCompanyNamePasses()
    {
        $data = $this->getValidClientData();
        $data['type'] = Client::TYPE_COMPANY;
        $data['company_name'] = 'Acme Pvt Ltd';

        $client = new Client();
        $client->load($data, '');

        $this->assertTrue($client->validate());
    }

    public function testDefaultStatusIsLead()
    {
        $client = new Client();
        $client->load($this->getValidClientData(), '');
        $client->save();

        $this->assertEquals(Client::STATUS_LEAD, $client->status);
    }

    public function testClientCodeAutoGenerated()
    {
        $data = $this->getValidClientData();
        unset($data['client_code']);

        $client = new Client();
        $client->load($data, '');
        $client->save();

        $this->assertNotEmpty($client->client_code);
        $this->assertStringContainsString('CLT-', $client->client_code);
    }

    public function testStatusList()
    {
        $list = Client::statusList();

        $this->assertArrayHasKey(Client::STATUS_LEAD, $list);
        $this->assertArrayHasKey(Client::STATUS_ACTIVE, $list);
        $this->assertArrayHasKey(Client::STATUS_BLOCKED, $list);
    }

    public function testTypeList()
    {
        $list = Client::typeList();

        $this->assertArrayHasKey(Client::TYPE_INDIVIDUAL, $list);
        $this->assertArrayHasKey(Client::TYPE_COMPANY, $list);
    }
}
